routes/web.php
<?php

use App\Http\Controllers\Contacts\ContactsController;
use App\Http\Controllers\Pages\AppointmentsCalendarController;
use App\Http\Controllers\Pages\DashboardController;

use App\Http\Controllers\Account\SettingsController;
use App\Http\Controllers\Auth\SocialiteLoginController;
use App\Http\Controllers\Logs\AuditLogsController;
use App\Http\Controllers\Logs\SystemLogsController;
use App\Http\Controllers\Pages\OrganizationExtensionsController;
use App\Http\Controllers\Pages\OrganizationIntegrationsController;
use App\Http\Controllers\Pages\OrganizationReportsController;
use App\Http\Controllers\Pages\OrganizationRolesController;
use App\Http\Controllers\Pages\OrganizationTeamsController;
use App\Http\Controllers\Pages\OrganizationUsersAddController;
use App\Http\Controllers\Pages\OrganizationUsersController;
use App\Http\Controllers\Pages\OrganizationUsersEditController;
use App\Http\Controllers\Pages\RealtimeController;
use App\Http\Controllers\Pages\ReportingController;
use App\Http\Controllers\Pages\ScriptsController;
use App\Http\Controllers\Pages\TasksController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect('index');
// });

$menu = theme()->getMenu();
array_walk($menu, function ($val) {
	if (isset($val['path'])) {
		$route = Route::get($val['path'], [PagesController::class, 'index']);

		// Exclude documentation from auth middleware
		//if (!Str::contains($val['path'], 'documentation')) {
		//    $route->middleware('auth');
		//}
	}
});


Route::middleware('auth')->group(function () {
	// Account pages
	Route::prefix('account')->group(function () {
		Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
		Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
		Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail');
		Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
	});

	// Logs pages
	Route::prefix('log')->name('log.')->group(function () {
		Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
		Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
	});
});

Route::resource('users', UsersController::class);

/**
 * Socialite login using Google service
 * https://laravel.com/docs/8.x/socialite
 */
Route::get('/auth/redirect/{provider}', [SocialiteLoginController::class, 'redirect']);

require __DIR__ . '/auth.php';


/* ROUTES LIST */

Route::middleware(['auth:web'])->group(function () {
	Route::get('', [DashboardController::class, 'index'])->name('dashboard.index');

	Route::prefix('contacts')->name('contacts.')->group(function () {
		Route::post('/filtered', [\App\Http\Controllers\Contacts\ContactsController::class, 'filteredIndex'])->name('filtered-index');
		Route::resource('', \App\Http\Controllers\Contacts\ContactsController::class)->parameter('', 'contact');
		Route::get('list', [ContactsController::class, 'index'])->name('contacts.index');
		Route::get('details', [ContactController::class, 'index'])->name('contact.index');
		Route::get('search', [ContactsSearchController::class, 'index'])->name('contacts.index');
		Route::get('create', [ContactsController::class, 'index'])->name('contacts.index');
		Route::get('import', [ContactsImportController::class, 'index'])->name('contacts.index1');


		Route::prefix('groups')->group(function () {
			Route::get('list', [ContactsGroupsController::class, 'index'])->name('contacts.groups.index');
		});
	});
	Route::prefix('communications')->group(function () {
		Route::get('list', [CommunicationsController::class, 'index'])->name('communications.index');
		Route::get('search', [CommunicationsSearchController::class, 'index'])->name('communications.search');
	});
	Route::prefix('tasks')->group(function () {
		Route::get('list', [TasksController::class, 'index'])->name('tasks.index');
		Route::get('create', [TasksController::class, 'add'])->name('tasks.add');
		Route::get('details', [TasksDetailsController::class, 'index'])->name('tasks.detail');
		Route::get('search', [TasksSearchController::class, 'index'])->name('tasks.search');
	});
	Route::prefix('appointments')->group(function () {
		Route::get('calendar', [AppointmentsCalendarController::class, 'index'])->name('appointments.calendar');
		Route::get('list', [AppointmentsListController::class, 'index'])->name('appointments.list');
		Route::get('search', [AppointmentsSearchController::class, 'index'])->name('appointments.search');
	});
	Route::prefix('scripts')->group(function () {
		Route::get('list', [ScriptsController::class, 'index'])->name('scripts.index');
	});
	Route::prefix('realtime')->group(function () {
		Route::get('list', [RealtimeController::class, 'index'])->name('realtime.index');
	});
	Route::prefix('reporting')->group(function () {
		Route::get('list', [ReportingController::class, 'index'])->name('reporting.index');
	});
	Route::prefix('organization')->name('organization.')->group(function () {
		Route::prefix('country-scopes')->name('country-scopes.')->group(function () {
			Route::get('/enable/{countryScopeId}', [\App\Http\Controllers\Organization\CountryScopesController::class, 'enable'])->name('enable');
			Route::get('/disable/{countryScope}', [\App\Http\Controllers\Organization\CountryScopesController::class, 'disable'])->name('disable');
			Route::post('/filtered', [\App\Http\Controllers\Organization\CountryScopesController::class, 'filteredIndex'])->name('filtered-index');
			Route::resource('', \App\Http\Controllers\Organization\CountryScopesController::class)->parameter('', 'countryScope');
		});
		Route::prefix('communication-types')->name('communication-types.')->group(function () {
			Route::post('/filtered', [\App\Http\Controllers\Organization\AccountCommunicationTypesController::class, 'filteredIndex'])->name('filtered-index');
			Route::resource('', \App\Http\Controllers\Organization\AccountCommunicationTypesController::class)->parameter('', 'accountCommunicationType');
		});
		Route::prefix('landing-pages')->name('landing-pages.')->group(function () {
			Route::post('/filtered', [\App\Http\Controllers\Organization\LandingPagesController::class, 'filteredIndex'])->name('filtered-index');
			Route::resource('', \App\Http\Controllers\Organization\LandingPagesController::class)->parameter('', 'landingPage');
		});
		Route::prefix('users')->group(function () {
			Route::get('/', [OrganizationUsersController::class, 'index'])->name('users.index');
			Route::get('/add', [OrganizationUsersAddController::class, 'index'])->name('users.index');
			Route::get('/edit', [OrganizationUsersEditController::class, 'index'])->name('users.index');
		});
		Route::get('reports', [OrganizationReportsController::class, 'index'])->name('reports.index');
		Route::get('integrations', [OrganizationIntegrationsController::class, 'index'])->name('integrations.index');
		Route::get('extensions', [OrganizationExtensionsController::class, 'index'])->name('extensions.index');
		Route::get('roles', [OrganizationRolesController::class, 'index'])->name('roles.index');
		Route::get('teams', [OrganizationTeamsController::class, 'index'])->name('teams.index');
	});

	Route::get('test', function () {
		return view('pages.test');
	});
});

app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
	/**
	 * Get the view / contents that represents the component.
	 */
	public function render()
	{
		if (theme()->getOption('layout', 'base') === 'docs') {
			return view('layout.docs.master');
		}

		return theme()->getView('layout.demo6.master');
	}
}

resources/views/pages/old_views/aside.blade.php
@php
    $menu = bootstrap()->getAsideMenu();
    /* \App\Core\Adapters\Menu::filterMenuPermissions($menu->items); */
@endphp

<div id="kt_aside" class="aside pb-5 pt-5 pt-lg-0" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'80px', '300px': '100px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle">
<!--begin::Brand-->
<div class="aside-logo py-8" id="kt_aside_logo">
    <!--begin::Logo-->
    <a href="../../demo6/dist/index.html" class="d-flex align-items-center">
        <img alt="Logo" src="assets/media/logos/logo-demo6.svg" class="h-45px logo" />
    </a>
    <!--end::Logo-->
</div>
<!--end::Brand-->
<!--begin::Aside menu-->
<div class="aside-menu flex-column-fluid" id="kt_aside_menu">
    <!--begin::Aside Menu-->
    <div class="hover-scroll-overlay-y my-2 my-lg-5 pe-lg-n1" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_aside_logo, #kt_aside_footer" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="5px">
        <!--begin::Menu-->
        <div class="menu menu-column menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500 fw-bold" id="#kt_aside_menu" data-kt-menu="true">
            {!! $menu->build() !!}
        </div>
        <!--end::Menu-->
    </div>
    <!--end::Aside Menu-->
</div>
<!--end::Aside menu-->
</div>

resources/views/pages/old_views/index.blade.php
<x-base-layout>

    <!--begin::Row-->
    <div class="row gy-5 g-xl-8">
        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/mixed/_widget-2', array('class' => 'card-xxl-stretch', 'chartColor' => 'danger', 'chartHeight' => '200px')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-5', array('class' => 'card-xxl-stretch')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/mixed/_widget-7', array('class' => 'card-xxl-stretch-50 mb-5 mb-xl-8', 'chartColor' => 'primary', 'chartHeight' => '150px')) }}

            {{ theme()->getView('partials/widgets/mixed/_widget-10', array('class' => 'card-xxl-stretch-50 mb-5 mb-xl-8', 'chartColor' => 'primary', 'chartHeight' => '175px')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

    <!--begin::Row-->
    <div class="row gy-5 gx-xl-8">
        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-3', array('class' => 'card-xxl-stretch mb-xl-3')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xl-8">
            {{ theme()->getView('partials/widgets/tables/_widget-9', array('class' => 'card-xxl-stretch mb-5 mb-xl-8')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

    <!--begin::Row-->
    <div class="row gy-5 g-xl-8">
        <!--begin::Col-->
        <div class="col-xl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-2', array('class' => 'card-xl-stretch mb-xl-8')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-6', array('class' => 'card-xl-stretch mb-xl-8')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xl-4">
            {{ theme()->getView('partials/widgets/lists/_widget-4', array('class' => 'card-xl-stretch mb-5 mb-xl-8', 'items' => '5')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

    <!--begin::Row-->
    <div class="row g-5 gx-xxl-8">
        <!--begin::Col-->
        <div class="col-xxl-4">
            {{ theme()->getView('partials/widgets/mixed/_widget-5', array('class' => 'card-xxl-stretch mb-xl-3', 'chartColor' => 'success', 'chartHeight' => '150px')) }}
        </div>
        <!--end::Col-->

        <!--begin::Col-->
        <div class="col-xxl-8">
            {{ theme()->getView('partials/widgets/tables/_widget-5', array('class' => 'card-xxl-stretch mb-5 mb-xxl-8')) }}
        </div>
        <!--end::Col-->
    </div>
    <!--end::Row-->

</x-base-layout>

resources/views/pages/old_views/toolbar.blade.php
<div class="toolbar py-2" id="kt_toolbar">
						<!--begin::Container-->
						<div id="kt_toolbar_container" class="container-fluid d-flex align-items-center">
							<!--begin::Page title-->
							<div class="flex-grow-1 flex-shrink-0 me-5">
								<!--begin::Page title-->
								<div data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}" class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
									<!--begin::Title-->
									<h1 class="d-flex align-items-center text-dark fw-bolder my-1 fs-3">Customer List</h1>
									<!--end::Title-->
									<!--begin::Separator-->
									<span class="h-20px border-gray-200 border-start mx-3"></span>
									<!--end::Separator-->
									<!--begin::Breadcrumb-->
									<ul class="breadcrumb breadcrumb-separatorless fw-bold fs-7 my-1">
										<!--begin::Item-->
										<li class="breadcrumb-item text-muted">
											<a href="../../demo6/dist/index.html" class="text-muted text-hover-primary">Home</a>
										</li>
										<!--end::Item-->
										<!--begin::Item-->
										<li class="breadcrumb-item">
											<span class="bullet bg-gray-200 w-5px h-2px"></span>
										</li>
										<!--end::Item-->
										<!--begin::Item-->
										<li class="breadcrumb-item text-muted">Apps</li>
										<!--end::Item-->
										<!--begin::Item-->
										<li class="breadcrumb-item">
											<span class="bullet bg-gray-200 w-5px h-2px"></span>
										</li>
										<!--end::Item-->
										<!--begin::Item-->
										<li class="breadcrumb-item text-muted">Customers</li>
										<!--end::Item-->
										<!--begin::Item-->
										<li class="breadcrumb-item">
											<span class="bullet bg-gray-200 w-5px h-2px"></span>
										</li>
										<!--end::Item-->
										<!--begin::Item-->
										<li class="breadcrumb-item text-dark">Customer Listing</li>
										<!--end::Item-->
									</ul>
									<!--end::Breadcrumb-->
								</div>
								<!--end::Page title-->
							</div>
							<!--end::Page title-->
							<!--begin::Action group-->
							<div class="d-flex align-items-center flex-wrap">
								<!--begin::Wrapper-->
								<div class="flex-shrink-0 me-2">
									<ul class="nav">
										<li class="nav-item">
											<a class="nav-link btn btn-sm btn-color-muted btn-active-color-primary btn-active-light active fw-bold fs-7 px-4 me-1" data-bs-toggle="tab" href="#">Day</a>
										</li>
										<li class="nav-item">
											<a class="nav-link btn btn-sm btn-color-muted btn-active-color-primary btn-active-light fw-bold fs-7 px-4 me-1" data-bs-toggle="tab" href="">Week</a>
										</li>
										<li class="nav-item">
											<a class="nav-link btn btn-sm btn-color-muted btn-active-color-primary btn-active-light fw-bold fs-7 px-4" data-bs-toggle="tab" href="#">Year</a>
										</li>
									</ul>
								</div>
								<!--end::Wrapper-->
								<!--begin::Wrapper-->
								<div class="d-flex align-items-center">
									<!--begin::Daterangepicker-->
									<a href="#" class="btn btn-sm btn-bg-light btn-color-gray-500 btn-active-color-primary me-2" id="kt_dashboard_daterangepicker" data-bs-toggle="tooltip" data-bs-dismiss="click" data-bs-trigger="hover" title="Select dashboard daterange">
										<span class="fw-bold me-1" id="kt_dashboard_daterangepicker_title">Range:</span>
										<span class="fw-bolder" id="kt_dashboard_daterangepicker_date">October 14</span>
									</a>
									<!--end::Daterangepicker-->
									<!--begin::Actions-->
									<div class="d-flex align-items-center">
										<button type="button" class="btn btn-sm btn-icon btn-color-primary btn-active-light btn-active-color-primary">
											<!--begin::Svg Icon | path: icons/duotune/files/fil005.svg-->
											<span class="svg-icon svg-icon-2x">
												<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
													<path opacity="0.3" d="M19 22H5C4.4 22 4 21.6 4 21V3C4 2.4 4.4 2 5 2H14L20 8V21C20 21.6 19.6 22 19 22ZM16 13H13V10C13 9.4 12.6 9 12 9C11.4 9 11 9.4 11 10V13H8C7.4 13 7 13.4 7 14C7 14.6 7.4 15 8 15H11V18C11 18.6 11.4 19 12 19C12.6 19 13 18.6 13 18V15H16C16.6 15 17 14.6 17 14C17 13.4 16.6 13 16 13Z" fill="black" />
													<path d="M15 8H20L14 2V7C14 7.6 14.4 8 15 8Z" fill="black" />
												</svg>
											</span>
											<!--end::Svg Icon-->
										</button>
									</div>
									<!--end::Actions-->
								</div>
								<!--end::Wrapper-->
							</div>
							<!--end::Action group-->
						</div>
						<!--end::Container-->
					</div>